In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [10]:
ar =np.array(l)
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
np.asarray(l)

array([1, 2, 3, 4])

In [12]:
a = [2,3,4]

In [13]:
np.asanyarray(a)

array([2, 3, 4])

In [18]:
b = np.matrix(l)

In [19]:
b

matrix([[1, 2, 3, 4]])

In [21]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [22]:
a = np.array(l)

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c = a

In [25]:
c

array([1, 2, 3, 4])

In [26]:
a

array([1, 2, 3, 4])

In [28]:
c[0] = 100

In [29]:
c

array([100,   2,   3,   4])

In [30]:
d = np.copy(a)

In [31]:
d

array([100,   2,   3,   4])

In [33]:
a[1] = 400

In [34]:
a

array([100, 400,   3,   4])

In [35]:
d

array([100,   2,   3,   4])

In [41]:
np.fromfunction(lambda i , j : i == j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i , j : i* j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
np.fromfunction(lambda i , j : i-j , (3,3))

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [43]:
iterable = (i*i for i  in range(5))

In [44]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [127]:
np.fromstring('323,348' , sep = '  ,  ')

array([323., 348.])

In [51]:
np.fromstring('4,5' , sep = ',')

array([4., 5.])

In [52]:
#numpy = Data Types.

In [53]:
l = [2,3,4,5,6]

In [54]:
ar = np.array(l)

In [55]:
ar

array([2, 3, 4, 5, 6])

In [56]:
ar.ndim

1

In [57]:
ar2 = np.array([[2,3,4], [5,6,7]])

In [58]:
ar2

array([[2, 3, 4],
       [5, 6, 7]])

In [60]:
ar2.ndim

2

In [61]:
ar2.size

6

In [63]:
ar.size

5

In [64]:
ar

array([2, 3, 4, 5, 6])

In [65]:
ar.shape

(5,)

In [66]:
ar2.shape

(2, 3)

In [67]:
ar2

array([[2, 3, 4],
       [5, 6, 7]])

In [68]:
ar.dtype

dtype('int64')

In [71]:
ar2.dtype

dtype('int64')

In [75]:
ar22 = np.array([(1.4,2,45,67), (4,5,7,643)])

In [76]:
ar22

array([[  1.4,   2. ,  45. ,  67. ],
       [  4. ,   5. ,   7. , 643. ]])

In [77]:
ar22.dtype

dtype('float64')

In [78]:
list(range(5))

[0, 1, 2, 3, 4]

In [80]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [82]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [84]:
list(np.arange(2.3,5.6, .3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [87]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [90]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [93]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [100]:
ar4 = np.zeros((3,4,2,3))

In [101]:
ar4.ndim

4

In [102]:
np.ones(4)

array([1., 1., 1., 1.])

In [103]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
on = np.ones((2,3,2))

In [107]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [108]:
on *4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [112]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [114]:
i = np.eye(4)

In [116]:
i + 5

array([[6., 5., 5., 5.],
       [5., 6., 5., 5.],
       [5., 5., 6., 5.],
       [5., 5., 5., 6.]])

In [117]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [121]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [129]:
arr =np.random.randn(3,4)

In [130]:
import pandas as pd

In [132]:
pd.DataFrame(arr)

0         1         2         3
0  0.840490  1.606898 -1.785132  0.108158
1  0.037432  0.777399  0.449945  1.489153
2 -1.896622 -0.929150 -1.344294  0.366326

In [136]:
import pandas as pd
rand = np.random.rand(3,4)
pd.DataFrame(rand)

0         1         2         3
0  0.489364  0.633836  0.393664  0.741261
1  0.199412  0.478393  0.672299  0.583919
2  0.956789  0.427081  0.505307  0.561059

In [140]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [144]:
pd.DataFrame(np.random.rand(3,4)).to_csv('test2.csv')

In [145]:
rand = np.random.rand(3,4)

In [146]:
rand

array([[0.6572487 , 0.30585789, 0.12339372, 0.88976341],
       [0.49938156, 0.68473405, 0.21214387, 0.18984822],
       [0.07286686, 0.30931461, 0.56508441, 0.26071227]])

In [151]:
art = rand.reshape(6,2)

In [152]:
art

array([[0.6572487 , 0.30585789],
       [0.12339372, 0.88976341],
       [0.49938156, 0.68473405],
       [0.21214387, 0.18984822],
       [0.07286686, 0.30931461],
       [0.56508441, 0.26071227]])

In [155]:
art[1][1]

0.8897634060962355

In [157]:
art[5][1]

0.2607122660164961

In [158]:
art[2:5]

array([[0.49938156, 0.68473405],
       [0.21214387, 0.18984822],
       [0.07286686, 0.30931461]])

In [161]:
art[2:5,1]

array([0.68473405, 0.18984822, 0.30931461])

In [167]:
art2 =np.random.randint(1,100,(5,5))

In [168]:
art2

array([[66, 65, 98, 37, 51],
       [70, 55, 99,  8,  4],
       [ 3, 21, 80, 89, 34],
       [77, 35,  7, 54, 96],
       [81, 90, 18, 47, 85]])

In [170]:
art2>50

[array([ True,  True,  True, False,  True]),
 array([ True,  True,  True, False, False]),
 array([False, False,  True,  True, False]),
 array([ True, False, False,  True,  True]),
 array([ True,  True, False, False,  True])]

In [171]:
art2[art2>50]

array([66, 65, 98, 51, 70, 55, 99, 80, 89, 77, 54, 96, 81, 90, 85])

In [172]:
art2

array([[66, 65, 98, 37, 51],
       [70, 55, 99,  8,  4],
       [ 3, 21, 80, 89, 34],
       [77, 35,  7, 54, 96],
       [81, 90, 18, 47, 85]])

In [177]:
art2[2:4,1:3]

array([[21, 80],
       [35,  7]])

In [178]:
art2[0][0] = 5000


In [179]:
art2

array([[5000,   65,   98,   37,   51],
       [  70,   55,   99,    8,    4],
       [   3,   21,   80,   89,   34],
       [  77,   35,    7,   54,   96],
       [  81,   90,   18,   47,   85]])

In [182]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))
                        

In [183]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [184]:
arr2

array([[1, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [185]:
arr1 +arr2

array([[2, 3, 3],
       [4, 3, 3],
       [2, 2, 4]])

In [186]:
arr1 -arr2

array([[ 0,  1, -1],
       [ 0, -1, -1],
       [ 0,  0,  0]])

In [187]:
arr1 /arr2

array([[1. , 2. , 0.5],
       [1. , 0.5, 0.5],
       [1. , 1. , 1. ]])

In [188]:
arr1 * arr2

array([[1, 2, 2],
       [4, 2, 2],
       [1, 1, 4]])

In [189]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [190]:
arr2

array([[1, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [191]:
arr1@arr2
#matrix multipication

array([[6, 6, 8],
       [5, 5, 8],
       [5, 5, 8]])

In [192]:
arr1 / 0

/tmp/ipykernel_459/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [193]:
arr1 + 100

array([[101, 102, 101],
       [102, 101, 101],
       [101, 101, 102]])

In [194]:
arr1 **2

array([[1, 4, 1],
       [4, 1, 1],
       [1, 1, 4]])

In [195]:
arr =np.zeros((4,4))

In [196]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [199]:
row = np.array([1,2,3,4])

In [203]:
row.shape

(4,)

In [200]:
row

array([1, 2, 3, 4])

In [201]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [204]:
row.T

array([1, 2, 3, 4])

In [207]:
col = np.array([[1,2,3,4]])

In [208]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [210]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [211]:
arr3 = np.random.randint(1,4,(3,4))

In [212]:
arr3

array([[2, 3, 3, 2],
       [1, 1, 2, 1],
       [2, 2, 2, 2]])