In [9]:
import numpy as np

In [10]:
#sort, search & counting functions

In [43]:
arr = np.array([1,2,3,4,5,6,7,8,11,9,10])

In [44]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.searchsorted(arr,34)

11

In [46]:
arr1 = np.array([0,345,450,0,0,0,0,0])

In [47]:
np.count_nonzero(arr1)

2

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [49]:
np.where(arr>6)

(array([ 6,  7,  8,  9, 10]),)

In [50]:
np.extract(arr>6, arr)

array([ 7,  8, 11,  9, 10])

In [51]:
np.extract(arr>3, arr)

array([ 4,  5,  6,  7,  8, 11,  9, 10])

In [52]:
arr.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680, 432345564227567616,
       504403158265495552, 576460752303423488, 792633534417207296,
       648518346341351424, 720575940379279360])

In [53]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [54]:
a = np.copy(arr)
#deep copy

In [55]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [56]:
b = arr.view()
#swallow copy

In [ ]:
b = arr

In [57]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [58]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [59]:
b[0] = 67

In [60]:
b

array([67,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [61]:
arr

array([67,  2,  3,  4,  5,  6,  7,  8, 11,  9, 10])

In [62]:
#numpy - matrixliberary

In [63]:
import numpy.matlib as nm

In [70]:
nm.zeros(3)

matrix([[0., 0., 0.]])

In [67]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
nm.eye(5)
#identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [72]:
ar1 = np.random.randint([[2,3], [4,5]])

In [73]:
ar2 = np.random.randint([[2,3], [4,5]])

In [74]:
ar1

array([[0, 1],
       [1, 0]])

In [75]:
ar2

array([[0, 2],
       [0, 0]])