In [89]:
import numpy as np

In [90]:
np.array([1,2,3])

array([1, 2, 3])

In [91]:
arr = np.random.randint(1,10,(3,4))

In [92]:
arr

array([[6, 8, 1, 8],
       [7, 5, 9, 4],
       [9, 9, 5, 5]])

In [93]:
arr.reshape(6,2)

array([[6, 8],
       [1, 8],
       [7, 5],
       [9, 4],
       [9, 9],
       [5, 5]])

In [94]:
arr.reshape(2,6)

array([[6, 8, 1, 8, 7, 5],
       [9, 4, 9, 9, 5, 5]])

In [95]:
arr.reshape(2, -34567)

array([[6, 8, 1, 8, 7, 5],
       [9, 4, 9, 9, 5, 5]])

In [96]:
arr.T

array([[6, 7, 9],
       [8, 5, 9],
       [1, 9, 5],
       [8, 4, 5]])

In [97]:
arr.flatten()

array([6, 8, 1, 8, 7, 5, 9, 4, 9, 9, 5, 5])

In [98]:
arr1 = np.array([1,2,3,4])

In [99]:
arr1

array([1, 2, 3, 4])

In [100]:
arr1.ndim

1

In [101]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 4]])

In [102]:
np.squeeze([arr])

array([[6, 8, 1, 8],
       [7, 5, 9, 4],
       [9, 9, 5, 5]])

In [103]:
data = np.array([[1],[2],[3], [4]])

In [104]:
data

array([[1],
       [2],
       [3],
       [4]])

In [105]:
np.squeeze([data])

array([1, 2, 3, 4])

In [106]:
arr1 

array([1, 2, 3, 4])

In [107]:
np.repeat(arr1, 3)
#use to repeat the element in array 


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [108]:
np.roll(arr1,shift = 3 )

array([2, 3, 4, 1])

In [109]:
arr1

array([1, 2, 3, 4])

In [110]:
arr1

array([1, 2, 3, 4])

In [111]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [112]:
#numpy - binary operation

In [113]:
arr12= np.random.randint(1,10,(3,4))


In [114]:
arr2= np.random.randint(1,10,(3,4))

In [115]:
arr12

array([[7, 7, 8, 4],
       [6, 1, 1, 8],
       [9, 7, 6, 3]])

In [116]:
arr2

array([[1, 1, 2, 7],
       [6, 3, 1, 6],
       [1, 3, 9, 8]])

In [117]:
arr2 + arr12

array([[ 8,  8, 10, 11],
       [12,  4,  2, 14],
       [10, 10, 15, 11]])

In [118]:
arr2 * arr12

array([[ 7,  7, 16, 28],
       [36,  3,  1, 48],
       [ 9, 21, 54, 24]])

In [119]:
arr2/arr12

array([[0.14285714, 0.14285714, 0.25      , 1.75      ],
       [1.        , 3.        , 1.        , 0.75      ],
       [0.11111111, 0.42857143, 1.5       , 2.66666667]])

In [120]:
arr2 - arr12

array([[-6, -6, -6,  3],
       [ 0,  2,  0, -2],
       [-8, -4,  3,  5]])

In [121]:
arr2 %arr12

array([[1, 1, 2, 3],
       [0, 0, 0, 6],
       [1, 3, 3, 2]])

In [122]:
arr1 ** arr12

array([[    1,   128,  6561,   256],
       [    1,     2,     3, 65536],
       [    1,   128,   729,    64]])

In [123]:
arr2 & arr12

array([[1, 1, 0, 4],
       [6, 1, 1, 0],
       [1, 3, 0, 0]])

In [124]:
arr2

array([[1, 1, 2, 7],
       [6, 3, 1, 6],
       [1, 3, 9, 8]])

In [125]:
arr12

array([[7, 7, 8, 4],
       [6, 1, 1, 8],
       [9, 7, 6, 3]])

In [126]:
- arr2

array([[-1, -1, -2, -7],
       [-6, -3, -1, -6],
       [-1, -3, -9, -8]])

In [127]:
arr2 | arr12

array([[ 7,  7, 10,  7],
       [ 6,  3,  1, 14],
       [ 9,  7, 15, 11]])

In [128]:
arr2>arr12

array([[False, False, False,  True],
       [False,  True, False, False],
       [False, False,  True,  True]])

In [129]:
#numpy = string operation

In [130]:
arr = np.array(['suraj', 'kumar'])

In [131]:
arr

array(['suraj', 'kumar'], dtype='<U5')

In [132]:
np.char.upper(arr)

array(['SURAJ', 'KUMAR'], dtype='<U5')

In [133]:
np.char.title(arr)

array(['Suraj', 'Kumar'], dtype='<U5')

In [134]:
np.char.capitalize(arr)

array(['Suraj', 'Kumar'], dtype='<U5')

In [135]:
#numpy - mathematical function 

In [136]:
arr1

array([1, 2, 3, 4])

In [137]:
arr2

array([[1, 1, 2, 7],
       [6, 3, 1, 6],
       [1, 3, 9, 8]])

In [138]:
np.sin(arr2)

array([[ 0.84147098,  0.84147098,  0.90929743,  0.6569866 ],
       [-0.2794155 ,  0.14112001,  0.84147098, -0.2794155 ],
       [ 0.84147098,  0.14112001,  0.41211849,  0.98935825]])

In [139]:
np.cos(arr2)

array([[ 0.54030231,  0.54030231, -0.41614684,  0.75390225],
       [ 0.96017029, -0.9899925 ,  0.54030231,  0.96017029],
       [ 0.54030231, -0.9899925 , -0.91113026, -0.14550003]])

In [140]:
np.tan(arr2)

array([[ 1.55740772,  1.55740772, -2.18503986,  0.87144798],
       [-0.29100619, -0.14254654,  1.55740772, -0.29100619],
       [ 1.55740772, -0.14254654, -0.45231566, -6.79971146]])

In [141]:
np.log(arr2)

array([[0.        , 0.        , 0.69314718, 1.94591015],
       [1.79175947, 1.09861229, 0.        , 1.79175947],
       [0.        , 1.09861229, 2.19722458, 2.07944154]])

In [142]:
np.exp(arr2)

array([[2.71828183e+00, 2.71828183e+00, 7.38905610e+00, 1.09663316e+03],
       [4.03428793e+02, 2.00855369e+01, 2.71828183e+00, 4.03428793e+02],
       [2.71828183e+00, 2.00855369e+01, 8.10308393e+03, 2.98095799e+03]])

In [143]:
np.sqrt(arr2)

array([[1.        , 1.        , 1.41421356, 2.64575131],
       [2.44948974, 1.73205081, 1.        , 2.44948974],
       [1.        , 1.73205081, 3.        , 2.82842712]])

In [145]:
np.power(arr2, 2)

array([[ 1,  1,  4, 49],
       [36,  9,  1, 36],
       [ 1,  9, 81, 64]])

In [146]:
np.mean(arr2)

4.0

In [148]:
np.mod(arr2)

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given